// <auto-generated />
namespace Proyecto_FunCase_WEBLY.FunCaseMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FunCaseInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FunCaseInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202107290651228_FunCaseInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
